# Generated by Django 3.2.18 on 2023-05-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
