# Generated by Django 3.2.18 on 2023-05-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='thumbnail',
            new_name='thumbnail_crop',
        ),
    ]
