# Generated by Django 3.2.18 on 2023-05-11 02:10

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230510_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
