# Generated by Django 3.2.18 on 2023-05-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230510_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review_image',
            old_name='review_id',
            new_name='review',
        ),
    ]
