# Generated by Django 3.2.18 on 2023-05-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
